### ISSUE TITLE
Prototype for linter plugin

### ISSUE THREAD

**Issue by michael-ciniawsky** [posthtml/posthtml-linter#1]
hey, i have a working prototype [posthtml-hint](https://github.com/michael-ciniawsky/posthtml-hint) for linting files with [htmlhint](https://github.com/yaniswang/HTMLHINT), simply wraps it and renders the tree as input, the log output (json) needs to be prettify for readability in some ways like this [htmlhint-stylish](https://github.com/doshprompt/htmlhint-stylish), i do it in as quickly as possible...

For the server-side i made [posthtml-tidy](https://github.com/michael-ciniawsky/posthtml-tidy), which fixed bad formatted html/xml on the fly with [W3C/HTACG](http://html-tidy.org)'s libtidy node wrapper.

Additionally i wrapped the W3C Validation Service (Semantics, ARIA, etc..) into a plugin [posthtml-w3c](https://github.com/michael-ciniawsky/posthrtml-w3c), but i'm not sure if it would be a better solution to enable this service in the linter plugin like: 
```js
 const hint = require('posthtml-hint')({config: './.htmlhintrc', validate:true})
```
?

**Comment by voischev** [comment]
Great job! :)
